# Generated by Django 4.0.2 on 2022-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
